name: Build to AWS ECR

on: push

jobs:
  login-to-aws:
     runs-on: ubuntu-latest
     steps:

     - name: Code Checkout
       uses: actions/checkout@v4

     - name: Login to AWS
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.REGION }}

  build-and-push-pub-ecr:
     runs-on: ubuntu-latest
     steps:

     - name: Code Checkout
       uses: actions/checkout@v4

     - name: Login to AWSECR
       uses: docker/login-action@v3
       with:
         registry: public.ecr.aws
         username: ${{ secrets.ACCESS_KEY }}
         password: ${{ secrets.SECRET_ACCESS_KEY }}
       env:
         aws-region: ${{ secrets.REGION }}

     - name: Build Image
       run: | 
         docker build -t merchant_api .
         docker tag merchant_api:latest public.ecr.aws/v6m2z7m5/merchant_api:v1
         docker push public.ecr.aws/v6m2z7m5/merchant_api:v1
     needs:
         login-to-aws:
     
